### ISSUE TITLE
Independent modules

### ISSUE THREAD

**Issue by eana** [howdio/terraform-aws-eks#8]
It would be really nice if this module could be split in two individual modules and call them together or not depending on what I need to create. I have this use case in which I need to create only the EKS cluster and the nodes with another module (which I could share when I will be done with it).

I could start working on this and create a PR if you think this might be useful.

@vlesierse what do you think?

**Comment by eana** [comment]
Another use case would be need more than one auto scaling group for the worker nodes.

**Comment by vlesierse** [comment]
HI @eana, thank you for your suggestion.
Currently the module is composed out of two submodules [`cluster`](https://registry.terraform.io/modules/howdio/eks/aws/0.3.1/submodules/cluster) and [`nodes`](https://registry.terraform.io/modules/howdio/eks/aws/0.3.1/submodules/nodes). This is exactly for the case your are describing.

If you look at the [`advanced`](https://github.com/howdio/terraform-aws-eks/blob/v0.3.1/examples/advanced/main.tf) example your can create an N number of node groups with their own auto scaling group. Please take a look and see if it covers and fit your use case. Otherwise we can look how we can support it.

**Comment by eana** [comment]
You are right, the advanced example covers that use case. However I believe that it would be better to add the addons (`kube2iam`, `dashboard` and `calico`) directly to the `cluster` sub-module as it makes more sense to have them in a single place.

I will open a PR and discuss my changes there.

**Comment by vlesierse** [comment]
@eana that sounds like a good idea. Makes more sense.

**Comment by eana** [comment]
PR was merged, closing the issue.
